version: '3'
services:
  db:
    image: "mongodb/mongodb-community-server:latest"
    container_name: "mongodb"
    ports:
      - "27017:27017"
    networks:
      - micro-app
    volumes:
      - mongo-data:/data/db
  webui:
    image: "pvu6800/webui:latest"
    container_name: "webui"
    ports:
      - "4200:4200"
    networks:
      - micro-app
  meo_mgnt:
    image: "pvu6800/meo-mgnt:latest"
    container_name: "meomgnt"
    ports:
      - "5000:5000"
    networks:
      - micro-app
    extra_hosts:
    - "host.docker.internal:host-gateway"
networks:
  micro-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local